In [51]:
import pandas as pd
# import numpy as np

In [52]:
list_order=pd.read_csv("List of Orders.csv")

In [53]:
list_order.head()

  Order ID  Order Date CustomerName           State       City
0  B-25601  01-04-2018       Bharat         Gujarat  Ahmedabad
1  B-25602  01-04-2018        Pearl     Maharashtra       Pune
2  B-25603  03-04-2018        Jahan  Madhya Pradesh     Bhopal
3  B-25604  03-04-2018       Divsha       Rajasthan     Jaipur
4  B-25605  05-04-2018      Kasheen     West Bengal    Kolkata

In [54]:
orders=pd.read_csv("order details.csv")

In [55]:
orders.head()

  Order ID  Amount  Profit  Quantity     Category      Sub-Category
0  B-25601  1275.0 -1148.0         7    Furniture         Bookcases
1  B-25601    66.0   -12.0         5     Clothing             Stole
2  B-25601     8.0    -2.0         3     Clothing       Hankerchief
3  B-25601    80.0   -56.0         4  Electronics  Electronic Games
4  B-25602   168.0  -111.0         2  Electronics            Phones

In [56]:
target = pd.read_csv("sales target.csv")

In [57]:
target.head()

  Month of Order Date   Category   Target
0              Apr-18  Furniture  10400.0
1              May-18  Furniture  10500.0
2              Jun-18  Furniture  10600.0
3              Jul-18  Furniture  10800.0
4              Aug-18  Furniture  10900.0

In [58]:
list_order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      500 non-null    object
 1   Order Date    500 non-null    object
 2   CustomerName  500 non-null    object
 3   State         500 non-null    object
 4   City          500 non-null    object
dtypes: object(5)
memory usage: 22.0+ KB

In [59]:
list_order['Order Date'] = pd.to_datetime(list_order['Order Date'],format='%d-%m-%Y')
# list_order['Order Date'] = pd.to_datetime(
#     list_order['Order Date'],
#     format='%d-%m-%Y'
# )

In [60]:
list_order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      500 non-null    object
 1   Order Date    500 non-null    datetime64[ns]
 2   CustomerName  500 non-null    object
 3   State         500 non-null    object
 4   City          500 non-null    object
dtypes: datetime64[ns](1), object(4)
memory usage: 22.0+ KB

In [61]:
list_order.shape

(560, 5)

In [62]:
list_order.describe

<bound method NDFrame.describe of     Order ID Order Date CustomerName           State       City
0    B-25601 2018-04-01       Bharat         Gujarat  Ahmedabad
1    B-25602 2018-04-01        Pearl     Maharashtra       Pune
2    B-25603 2018-04-03        Jahan  Madhya Pradesh     Bhopal
3    B-25604 2018-04-03       Divsha       Rajasthan     Jaipur
4    B-25605 2018-04-05      Kasheen     West Bengal    Kolkata
..       ...        ...          ...             ...        ...
555      NaN        NaT          NaN             NaN        NaN
556      NaN        NaT          NaN             NaN        NaN
557      NaN        NaT          NaN             NaN        NaN
558      NaN        NaT          NaN             NaN        NaN
559      NaN        NaT          NaN             NaN        NaN

[560 rows x 5 columns]>

In [63]:
list_order['Order ID'].duplicated().sum()

np.int64(59)

In [64]:
list_order.isnull().sum()

Order ID        60
Order Date      60
CustomerName    60
State           60
City            60
dtype: int64

In [65]:
list_order=list_order.dropna(how='all')

In [66]:
list_order.isnull().sum()

Order ID        0
Order Date      0
CustomerName    0
State           0
City            0
dtype: int64

In [67]:
list_order.shape

(500, 5)

In [68]:
list_order['Order ID'].duplicated().sum()

np.int64(0)

In [69]:
list_order['Order Date'].head()

0   2018-04-01
1   2018-04-01
2   2018-04-03
3   2018-04-03
4   2018-04-05
Name: Order Date, dtype: datetime64[ns]

In [70]:
orders.tail(6)

     Order ID  Amount  Profit  Quantity     Category Sub-Category
1494  B-26099   207.0    37.0         4     Clothing  Hankerchief
1495  B-26099   835.0   267.0         5  Electronics       Phones
1496  B-26099  2366.0   552.0         5     Clothing     Trousers
1497  B-26100   828.0   230.0         2    Furniture       Chairs
1498  B-26100    34.0    10.0         2     Clothing      T-shirt
1499  B-26100    72.0    16.0         2     Clothing        Shirt

In [71]:
orders.shape

(1500, 6)

In [72]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Amount        1500 non-null   float64
 2   Profit        1500 non-null   float64
 3   Quantity      1500 non-null   int64
 4   Category      1500 non-null   object
 5   Sub-Category  1500 non-null   object
dtypes: float64(2), int64(1), object(3)
memory usage: 70.4+ KB

In [73]:
orders.dtypes

Order ID         object
Amount          float64
Profit          float64
Quantity          int64
Category         object
Sub-Category     object
dtype: object

In [74]:
orders['Order ID'].nunique()

500

In [75]:
orders['Order ID'].duplicated().sum()

np.int64(1000)

In [76]:
orders.duplicated().sum()

np.int64(0)

In [77]:
orders.isnull().sum()

Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
dtype: int64

In [78]:
target.shape

(36, 3)

In [79]:
target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Month of Order Date  36 non-null     object
 1   Category             36 non-null     object
 2   Target               36 non-null     float64
dtypes: float64(1), object(2)
memory usage: 996.0+ bytes

In [80]:
target.isnull().sum()

Month of Order Date    0
Category               0
Target                 0
dtype: int64

In [81]:
target.duplicated().sum()

np.int64(0)

In [82]:
target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Month of Order Date  36 non-null     object
 1   Category             36 non-null     object
 2   Target               36 non-null     float64
dtypes: float64(1), object(2)
memory usage: 996.0+ bytes

In [83]:
target['Month of Order Date']= pd.to_datetime(target['Month of Order Date'],format='%b-%y')

In [84]:
target.dtypes

Month of Order Date    datetime64[ns]
Category                       object
Target                        float64
dtype: object

In [85]:
target['Month of Order Date'].head()

0   2018-04-01
1   2018-05-01
2   2018-06-01
3   2018-07-01
4   2018-08-01
Name: Month of Order Date, dtype: datetime64[ns]

EDA

In [86]:
list_order['CustomerName'].nunique()

332

In [87]:
list_order['CustomerName'].value_counts()

CustomerName
Shreya      6
Shubham     5
Abhishek    5
Pooja       5
Sheetal     4
           ..
Sukant      1
Sukrith     1
Sauptik     1
Shishu      1
Ankita      1
Name: count, Length: 332, dtype: int64

In [88]:
(list_order['CustomerName'].value_counts() > 1).sum()

np.int64(103)

In [89]:
#Revenue
orders['Amount'].sum()

np.float64(431502.0)

In [90]:
#profit
orders['Profit'].sum()

np.float64(23955.0)

In [91]:
#Profit margin
orders['Profit'].sum()/order['Amount'].sum() * 100

np.float64(5.551538579195461)

In [92]:
#total unit sold
orders['Quantity'].sum()

np.int64(5615)

In [93]:
import pandas as pd
from sqlalchemy import create_engine

username = "root"
password = "Prabhu%401967"
host = "localhost"
port = "3306"
database = "E_Commerce"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# table_name = "mytable"

# Upload DataFrame to MySQL
list_order.to_sql("list_order", engine, if_exists="replace", index=False)
orders.to_sql("orders", engine, if_exists="replace", index=False)
target.to_sql("target", engine, if_exists="replace", index=False)

36